apiVersion: v1
kind: Secret
metadata:
  name: auth-social-oauth2
  namespace: puchi-backend
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  FACEBOOK_CLIENT_ID: ""
  FACEBOOK_CLIENT_SECRET: ""
  TIKTOK_CLIENT_ID: ""
  TIKTOK_CLIENT_SECRET: ""
