apiVersion: v1
kind: Secret
metadata:
  name: auth-social-oauth2
  namespace: puchi-backend
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  FACEBOOK_CLIENT_ID: ""
  FACEBOOK_CLIENT_SECRET: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-limen-secret
  namespace: puchi-backend
type: Opaque
stringData:
  # Must be exactly 32 bytes
  LIMEN_SECRET: "CHANGE_ME_32_BYTE_LIMEN_SECRET!!"
