apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-puchi
  namespace: puchi-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0

  storage:
    size: 10Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: puchi
      owner: puchi
      secret:
        name: pg-puchi-app-secret

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

  monitoring:
    enablePodMonitor: true
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-puchi-app-secret
  namespace: puchi-db
type: kubernetes.io/basic-auth
stringData:
  username: puchi
  password: puchi-db-prod
---
# DB cho Supertoken — CNPG sẽ tạo database riêng
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-supertokens
  namespace: puchi-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0

  storage:
    size: 5Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: supertokens
      owner: supertokens
      secret:
        name: pg-supertokens-secret

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-supertokens-secret
  namespace: puchi-db
type: kubernetes.io/basic-auth
stringData:
  username: supertokens
  password: sup3rt0k3ns
