apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  namespace: puchi-backend
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
    data:
      database:
        driver: postgres
        source: postgres://puchi:puchi-db-prod@pg-puchi-rw.puchi-db.svc.cluster.local:5432/puchi?sslmode=disable
      redis:
        addr: valkey-node-0.platform.svc.cluster.local:6379
        read_timeout: 0.2s
        write_timeout: 0.2s
    auth:
      zitadel:
        issuer_url: "https://auth.puchi.io.vn"
        jwks_url: "https://auth.puchi.io.vn/oauth/v2/keys"
      public_paths:
        - /auth
        - /v1/health
        - /v1/healthz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: puchi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: ghcr.io/puchidemy/puchi-core:git-fedad8f
          ports:
            - containerPort: 8000
            - containerPort: 9000
          command: ["./core", "-conf", "/data/conf"]
          volumeMounts:
            - name: config
              mountPath: /data/conf
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: core-config
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: puchi-backend
spec:
  selector:
    app: core
  ports:
    - name: grpc
      port: 8000
      targetPort: 8000
    - name: debug
      port: 9000
      targetPort: 9000
