apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: puchi-api-security
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: puchi-api-routes
  cors:
    allowOrigins:
      - "https://puchi.io.vn"
      - "http://localhost:3000"
    allowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowHeaders:
      - content-type
      - authorization
      - x-requested-with
    exposeHeaders:
      - content-type
    allowCredentials: true
