apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatewayclass.yaml
  - gateway.yaml
  - httproute.yaml
  - envoyproxy.yaml
  - reference-grant.yaml
  - puchi-api-service.yaml
  - security-policy.yaml
