apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: puchi-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: web
          image: ghcr.io/puchidemy/puchi-frontend:git-ad176b5
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_APP_URL
              value: "https://puchi.io.vn"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.puchi.io.vn"
            - name: NEXT_PUBLIC_WEBSITE_DOMAIN
              value: "https://puchi.io.vn"
            - name: NODE_ENV
              value: "production"
            - name: AUTH_URL
              value: "https://puchi.io.vn"
            - name: NEXTAUTH_URL
              value: "https://puchi.io.vn"
            - name: ZITADEL_CLIENT_ID
              value: "382000685111116512"
            - name: ZITADEL_ISSUER
              value: "https://auth.puchi.io.vn"
            - name: ZITADEL_INTERNAL_URL
              value: "https://auth.puchi.io.vn"
            - name: ZITADEL_SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: zitadel-credentials
                  key: ZITADEL_SERVICE_TOKEN
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: zitadel-credentials
                  key: AUTH_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-credentials
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-credentials
                  key: GOOGLE_CLIENT_SECRET
            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-credentials
                  key: FACEBOOK_CLIENT_ID
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-credentials
                  key: FACEBOOK_CLIENT_SECRET
            - name: TIKTOK_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth-credentials
                  key: TIKTOK_CLIENT_KEY
            - name: TIKTOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-credentials
                  key: TIKTOK_CLIENT_SECRET
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: puchi-frontend
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
