apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: puchi-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: web
          image: ghcr.io/puchidemy/puchi-frontend:git-8687d2e
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_APP_URL
              value: "https://puchi.io.vn"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.puchi.io.vn"
            - name: NEXT_PUBLIC_WEBSITE_DOMAIN
              value: "https://puchi.io.vn"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: puchi-frontend
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
