apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: puchi-backend-core
  namespace: argocd
spec:
  project: puchi
  source:
    repoURL: 'https://github.com/puchidemy/puchi-infra'
    targetRevision: main
    path: infra/backend/core
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: puchi-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: puchi-backend-learn
  namespace: argocd
spec:
  project: puchi
  source:
    repoURL: 'https://github.com/puchidemy/puchi-infra'
    targetRevision: main
    path: infra/backend/learn
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: puchi-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: puchi-backend-media
  namespace: argocd
spec:
  project: puchi
  source:
    repoURL: 'https://github.com/puchidemy/puchi-infra'
    targetRevision: main
    path: infra/backend/media
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: puchi-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: puchi-backend-notification
  namespace: argocd
spec:
  project: puchi
  source:
    repoURL: 'https://github.com/puchidemy/puchi-infra'
    targetRevision: main
    path: infra/backend/notification
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: puchi-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: puchi-backend-auth
  namespace: argocd
spec:
  project: puchi
  source:
    repoURL: 'https://github.com/puchidemy/puchi-infra'
    targetRevision: main
    path: infra/backend/auth
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: puchi-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
