apiVersion: v1
kind: Secret
metadata:
  name: puchi-github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/puchidemy
  username: git
  password: ""  # managed manually on cluster
type: Opaque
