apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
spec:
  project: puchi
  source:
    repoURL: 'https://github.com/puchidemy/puchi-infra'
    targetRevision: main
    path: infra/zitadel
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: puchi-auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
