replicaCount: 1

zitadel:
  masterkeySecretName: zitadel-masterkey
  configmapConfig:
    ExternalDomain: auth.puchi.io.vn
    ExternalSecure: true
    ExternalPort: 443
    TLS:
      Enabled: false
    Database:
      postgres:
        Host: pg-main-rw.database.svc.cluster.local
        Port: 5432
        Database: zitadel
        User:
          Username: zitadel
          Password: z1tadelpass123
        Admin:
          Username: postgres
          Password: x2wh1KJRZNbKHyqIldeDVZ9cPLSWMdTrPAcsg5MNSGLyt50U6XQ8Bostxkpz4YJ3
        SSL:
          Mode: disable
    FirstInstance:
      Org:
        Human:
          UserName: "admin"
          Password: "P@ssword1!"
          FirstName: "Zitadel"
          LastName: "Admin"
          Email: "admin@puchi.io.vn"
          PasswordChangeRequired: true

postgresql:
  enabled: false

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: auth.puchi.io.vn
      paths:
        - path: /
          pathType: Prefix

login:
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: auth.puchi.io.vn
        paths:
          - path: /ui/v2/login
            pathType: Prefix
