apiVersion: v1
kind: ConfigMap
metadata:
  name: media-config
  namespace: puchi-backend
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
    data:
      database:
        driver: postgres
        source: postgres://puchi:puchi-db-prod@pg-puchi-rw.puchi-db.svc.cluster.local:5432/puchi?sslmode=disable
      redis:
        addr: valkey-node-0.platform.svc.cluster.local:6379
        read_timeout: 0.2s
        write_timeout: 0.2s
    auth:
      auth_service_url: "http://auth-service.puchi-backend:8080"
      public_paths:
        - /v1/health
        - /v1/healthz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media
  namespace: puchi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: media
          image: ghcr.io/puchidemy/puchi-media:git-ce58706
          ports:
            - containerPort: 8000
            - containerPort: 9000
          command: ["./media", "-conf", "/data/conf"]
          volumeMounts:
            - name: config
              mountPath: /data/conf
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: media-config
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: puchi-backend
spec:
  selector:
    app: media
  ports:
    - name: grpc
      port: 8000
      targetPort: 8000
    - name: debug
      port: 9000
      targetPort: 9000
