apiVersion: v1
kind: Service
metadata:
  name: st-core-svc
  namespace: puchi-infra
spec:
  type: NodePort
  selector:
    app: st-core
  ports:
    - port: 3567
      targetPort: 3567
      nodePort: 30567
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-core
  namespace: puchi-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: st-core
  template:
    metadata:
      labels:
        app: st-core
    spec:
      containers:
        - name: supertokens
          image: supertokens/supertokens-postgresql:11.3
          ports:
            - containerPort: 3567
          env:
            - name: POSTGRESQL_CONNECTION_URI
              value: "postgresql://supertokens:sup3rt0k3ns@pg-supertokens-rw.puchi-db.svc.cluster.local:5432/supertokens"
            - name: API_KEYS
              value: "change-in-production-please"
