apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: puchi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: ghcr.io/puchidemy/puchi-notification:latest
          ports:
            - containerPort: 8000
            - containerPort: 9000
          command: ["./notification", "-conf", "/data/conf"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: puchi-backend
spec:
  selector:
    app: notification
  ports:
    - name: grpc
      port: 8000
      targetPort: 8000
    - name: debug
      port: 9000
      targetPort: 9000
